spring:
  application:
    name: BLPS_Lab1
  datasource:
    url: jdbc:postgresql://postgres:5432/first?autoReconnect=true&useSSL=false
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  
    database-platform: org.hibernate.dialect.PostgreSQLDialect