spring:
  application:
    name: BLPS_Lab1
  datasource:
    url: jdbc:postgresql://localhost:5432/first
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
token:
  signing:
    key: Q5v1CXQ1Y64cayU84BnlR3Az9fVFe8Bvn6Mrf68bX5U=