services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "first"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    # volumes:
    #   - ./init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"


#mvn clean install && docker compose down -v && docker compose build && docker compose up