spring:
  jta:
    enabled: true
  application:
    name: BLPS_Lab1
  datasource:
    url: jdbc:postgresql://localhost:5432/first
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.mail.ru
    port: 465
    username: hokure04@mail.ru
    password: aHXm4xap2rkyg4dS4hL5
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
minio:
  endpoint: "http://localhost:9000"
  root:
    username:
      JABA_SUPER_USER_MINIO
    pwd:
      jaba127!368601NO

token:
  signing:
    key: Q5v1CXQ1Y64cayU84BnlR3Az9fVFe8Bvn6Mrf68bX5U=
certificate:
  generator:
    pdf: "/Users/jaba/Documents/life/learning_extra/BLPS_Labs/BLPS_Lab1/подпись.png"
narayana:
  messaginghub:
    maxConnections: 10
    max_prepared_transactions: 100
app:
  admin:
    username: admin@admin.admin
    password: admin