FROM bitnami/keycloak:26.2.0

#COPY registration-manager/build/libs/*.jar /opt/bitnami/keycloak/providers/registration-manager-1.0-SNAPSHOT.jar


ENTRYPOINT ["/opt/bitnami/scripts/keycloak/entrypoint.sh"]
CMD ["/opt/bitnami/scripts/keycloak/run.sh"]